name: Build Logseq theme

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  PLUGIN_NAME: logseq-plugin-remember-my-block

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run prod

      - name: Package plugin
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp -r dist/ ${{ env.PLUGIN_NAME }}/
          cp package.json ${{ env.PLUGIN_NAME }}/
          cp README.md ${{ env.PLUGIN_NAME }}
          cp Remember_my_block-plugin_disabled.gif ${{ env.PLUGIN_NAME }}
          cp Remember_my_block-plugin_enabled.gif ${{ env.PLUGIN_NAME }}
          cp LICENSE ${{ env.PLUGIN_NAME }}
          cp icon.svg ${{ env.PLUGIN_NAME }} || true
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            package.json
          generate_release_notes: true
          draft: false
